use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // Try to read build-info.json (generated by npm prebuild hook)
    let build_info_path = Path::new("../build-info.json");

    if build_info_path.exists() {
        let contents =
            fs::read_to_string(build_info_path).expect("Failed to read build-info.json");
        let info: serde_json::Value =
            serde_json::from_str(&contents).expect("Invalid build-info.json");

        if let Some(bn) = info["buildNumber"].as_str() {
            println!("cargo:rustc-env=BUILD_NUMBER={}", bn);
        }
        if let Some(bd) = info["buildDate"].as_str() {
            println!("cargo:rustc-env=BUILD_DATE={}", bd);
        }
        if let Some(gc) = info["gitCommit"].as_str() {
            println!("cargo:rustc-env=GIT_COMMIT={}", gc);
        }
    } else {
        // Fallback: populate git commit for local dev builds
        let git_commit = Command::new("git")
            .args(["rev-parse", "--short", "HEAD"])
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .unwrap_or_else(|| "unknown".to_string());

        println!("cargo:rustc-env=GIT_COMMIT={}", git_commit);
        // BUILD_NUMBER and BUILD_DATE are left unset so option_env!() returns None/"dev"
    }

    // Re-run build script if build-info.json changes
    println!("cargo:rerun-if-changed=../build-info.json");

    tauri_build::build()
}
